Tutorial
Zubax/zubax_documentation_portal pull request #11
Opened 2016-11-25 04:38 UTC by j3qq4hch

2016-11-25 05:17 UTC, ctech4285 commented
wow I am glad I am not the only one submitting mergers titles 'blah'

2016-11-25 05:17 UTC, j3qq4hch commented
I am doing that after you

2016-11-25 05:19 UTC, pavel-kirienko commented
Blah. Sorry just felt like saying something.

2016-11-25 05:21 UTC, pavel-kirienko requested changes
Alexander, if you could replace the screenshots with English languaged ones, that would be great. Also please enable syntax highlighting, it works like that:

    ```c++
    int main()
    {
        std::puts("C++ code goes here");
        return 0;
    }
    ```

2016-11-25 05:22 UTC, pavel-kirienko commented
You will likely greatly benefit from reading this https://guides.github.com/features/mastering-markdown/.

2016-11-25 05:24 UTC, j3qq4hch commented
>>Alexander, if you could replace the screenshots with English languaged ones
I tried that, but I've got only Win10 ONE LANGUAGE version. That looks like nonsense, but I can't switch GUI language in my OS at all.

2016-11-25 05:36 UTC, pavel-kirienko commented
This should help (crop as necessary):

![virtualbox_win8_25_11_2016_08_33_30](https://cloud.githubusercontent.com/assets/3298404/20615347/0d89cc58-b2ea-11e6-87e6-f97a6fd84f6c.png)

You can also grab a free [Windows 10 image for VirtualBox from Microsoft directly (no joke)](https://www.microsoft.com/ru-RU/software-download/windows10).

2016-11-25 05:36 UTC, j3qq4hch commented
Thanks!

2016-11-28 20:55 UTC, pavel-kirienko commented
Hey @j3qq4hch, here's some feedback.

- [ ] I propose to not spread the content over multiple articles, but join it instead into one large article. This would be coherent with the way the rest of the website is organized.
- [ ] The code needs to be properly formatted and syntax highlighted (see my example above).
- [ ] Tabs are not allowed anywhere, use spaces. Tabs do not render correctly.
- [ ] Commands are case sensitive in some OS, so `Git` is not the same thing as `git`. I know that in Windows it wouldn't matter, but the universal convention is to always use lower case.
- [ ] I believe we've discussed earlier that it makes sense to make different sections for Windows and Linux based hosts. The latter one would be empty for now, but it makes sense to structure the content in a way that allows for its easy extension later. E.g. you could put your "coming soon" under the Linux section as a space filler.
- [ ] Please never forget to use proper typography. File system paths and code samples should be enclosed into a pair of single backticks (see the Markdown reference above). Also don't hesitate to explicitly structure the content using nested headers - this allows the website engine to generate neat and easily navigable table of contents on the left sidebar under the menu. For example, the two sections that describe how to flash the firmware via DCP and via the bootloader should definitely be nested into a common section.
- [ ] Minor punctuation and stylistic errors, e.g. missing commas after "finally", and inappropriate upper case, e.g. BABEL instead of Babel. This is a very public website, so we must ensure that everything looks as perfect as possible. You could use the [user manual page for Babel](https://docs.zubax.com/zubax_babel) as an inspiration.
- [ ] It's best to avoid C whenever possible. How about replacing all `THD_FUNCTION(....)` with `class MyThread : public chibios_rt::BaseStaticThread<512> { ... };`, and such? You can find plenty of examples in the main firmware. Compared to C, C++ offers higher expressiveness and better type safety, which allows to write more concise and reliable code. Also see [this](https://github.com/Zubax/zubax_style_guide).

2016-12-01 12:50 UTC, pavel-kirienko commented
@j3qq4hch nudge

2016-12-01 12:52 UTC, j3qq4hch commented
Indeed. Will fix it

2016-12-03 17:54 UTC, j3qq4hch commented
You see, the main goal of this tutorial is to allow a person to start. I believe it is easier in C. After all, ChibiOS is written in C and its manuals and examples use C too.

2016-12-03 17:59 UTC, j3qq4hch commented
BTW, why are we using english in this issue?!

2016-12-03 19:13 UTC, pavel-kirienko commented
Please check the page in a web browser, it is not rendering correctly.

The section dedicated to build dependencies should be split into Windows and Linux/OSX sub-sections.

Proper ordering of headings must be maintained. Heading level 1 is the name of the article, so only one such heading is allowed. Headers level 2+ are sections of the article. Heading level X may be a direct parent only to headers level X+1 (you are jumping from 1 to 3).

Typographic issues have not been fixed so I unchecked the corresponding item in the list above. You may find the single backtick syntax useful for highlighting one liners:

```
If everything is fine, you will find `compound.elf` in directory `/%reponame%/firmware/build/`.
```

I propose to provide complete source of `main.cpp` in the tutorials rather than diffs. Components that are known to not be used by the user application should also be removed, e.g. CAN and USB drivers. The diff based approach will leave the user with a ton of garbage code in their projects.

> You see, the main goal of this tutorial is to allow a person to start. I believe it is easier in C.

It would be a valid point if we were working on a general programming tutorial. Since we aren't, the learning curve argument should not apply. As for advantages of C++ over C in our case:

- C++ is probably a better choice for software development in general because of higher level abstractions and stronger safety guarantees. It makes sense to propagate better practices whenever possible.
- The main firmware is written in C++, so the reader will be able to use it as a reference.
- The Zubax ChibiOS libraries are written in C++ and have no C bindings. These libraries implement important features like non-volatile configuration parameter storage and some useful helpers.

Speaking of configuration parameters, why not include one or two in the second tutorial?

> why are we using english in this discussion?

This is a public repo, we don't know who could be reading.

2016-12-03 19:27 UTC, j3qq4hch commented
>>The section dedicated to build dependencies should be split into Windows and Linux/OSX sub-sections.
There is no need to split this as it is absolutely the same on win and *nix
What really differs(not much though) is flashing the firmware. 

I must also say I'm not really good at C++ and much more used to C. 
Lets leave first blinking tutorials in C and the third one, which will use command line interface and parameter storing will be in C++.

2016-12-03 19:27 UTC, pavel-kirienko commented
To further expand on this:

> I propose to provide complete source of main.cpp in the tutorials rather than diffs. Components that are known to not be used by the user application should also be removed, e.g. CAN and USB drivers. The diff based approach will leave the user with a ton of garbage code in their projects.

It might make sense to set up a dedicated directory for user-specific applications in the firmware repo as follows:

```
├── firmware
│   ├── ld.ld
│   ├── Makefile
│   ├── src/
│   └── zubax_chibios/
├── custom_firmware_template
│   ├── ld.ld                   - Symlink to firmware/ld.ld
│   ├── Makefile                - Custom
│   ├── src
│   │   ├── main.cpp            - Custom
│   │   ├── usb_cdc.hpp         - Copy from firmware/
│   │   ├── usb_cdc.cpp         - Sliglty modified copy from firmware/
│   │   ├── board/              - Sliglty modified copy from firmware/
│   │   └── sys/                - Sliglty modified copy from firmware/
│   └── zubax_chibios/          - Symlink to firmware/zubax_chibios
├── hardware
├── bootloader
└── <...>
```

2016-12-03 19:30 UTC, j3qq4hch commented
I must admit it, WYSIWYG MD editors can't produce proper MD-pages for some reason. 
What do you use for preview?

2016-12-03 19:37 UTC, pavel-kirienko commented
> There is no need to split this as it is absolutely the same on win and *nix

It isn't - gnu utils and Python need not be installed on anything but Windows.

> Lets leave first blinking tutorials in C and the third one, which will use command line interface and parameter storing will be in C++.

The only major difference between C and C++ in the first two tutorials would be the way threads are defined and launched. This is the correct way:

```c++
class MyThread : public chibios_rt::BaseStaticThread<1024>
{
    void main() override
    {
        setName("blinker");
        palSetPadMode(GPIOE, 8, PAL_MODE_OUTPUT_PUSHPULL);
        while (true)
        {
            palSetPad(GPIOE,8);
            chThdSleepMilliseconds(100);
            palClearPad(GPIOE, 8);
            chThdSleepMilliseconds(100);
        }
    }

public:
    virtual ~MyThread() { }
} thread_;

int main()
{
    auto watchdog = app::init();
    thread_.start(NORMALPRIO + 1);
    while(1)
    {
        watchdog.reset();
    }
}
```

2016-12-03 19:39 UTC, pavel-kirienko commented
> I must admit it, WYSIWYG MD editors can't produce proper MD-pages for some reason.
> What do you use for preview?

I write in a regular text editor and use a local instance of the website for preview.

2016-12-03 19:41 UTC, pavel-kirienko commented
In the second tutorial, `pwmcfg` must be declared `const`.

2016-12-21 22:11 UTC, pavel-kirienko commented
Nudge nudge

2016-12-21 22:47 UTC, ctech4285 commented
This is too long for me to read

2016-12-21 22:48 UTC, pavel-kirienko commented
We'll make a movie out of it someday.

2016-12-22 16:55 UTC, ctech4285 commented
We shall call it Moscow Valley

2016-12-27 16:07 UTC, pavel-kirienko commented
@j3qq4hch You didn't review the changes, apparently. Please always do so.

C sections are not needed, we should constrain ourselves to C++ only.

2016-12-27 16:13 UTC, j3qq4hch commented
Come on. Let's leave a couple of them just to demonstrate a variety of possibilities.

2016-12-27 16:14 UTC, pavel-kirienko requested changes

2016-12-27 16:14 UTC, pavel-kirienko commented on 0 Products/40 Zubax Babel/Tutorials/10 Developing custom applications.md
> +Now find function ```int main()``` in ```zubax_babel\firmware\src\main.cpp```. This is program entry point. Comment it all and write your own version like this:
Here and elsewhere: inline code blocks are highlighted with single backticks: ``` `code` ```. Triple backticks are needed to highlight multi-line code blocks.

2016-12-27 16:14 UTC, pavel-kirienko commented on 0 Products/40 Zubax Babel/Tutorials/10 Developing custom applications.md
> +```git clone https://github.com/Zubax/zubax_babel```
Are you sure it is necessary to put such a simple command on a separate line? Also, missing punctuation at the end of the previous line.

2016-12-27 16:14 UTC, pavel-kirienko commented on 0 Products/40 Zubax Babel/Tutorials/10 Developing custom applications.md
> +Now add breath_thread to you code:
Broken formatting

2016-12-27 16:14 UTC, pavel-kirienko commented on 0 Products/40 Zubax Babel/Tutorials/10 Developing custom applications.md
> +```
Missing syntax highlight directive: `c++`

2016-12-27 16:14 UTC, pavel-kirienko commented on 0 Products/40 Zubax Babel/Tutorials/10 Developing custom applications.md
> +  255,                                      //255 ticks is pwm resolution
Missing space at the beginning of the comments. I admit our style guide does not say anything about this, this is my fault; I will update it right now.

2016-12-27 16:16 UTC, j3qq4hch commented on 0 Products/40 Zubax Babel/Tutorials/10 Developing custom applications.md
> +```
So we need to highlight programming language name too?

2016-12-27 16:16 UTC, pavel-kirienko commented
> variety of possibilities

What for? C is generally inferior to C++ in terms of code readability, safety, and performance (when used properly) (I hate both though). Keeping C code samples would only increase maintenance workload.

2016-12-27 16:18 UTC, j3qq4hch commented
What if some c-guy(like me) would like to use babel?

2016-12-27 16:21 UTC, pavel-kirienko commented
They would have to learn basic C++, it's not hard, and there are **helpful tutorials** to the rescue!

2016-12-27 16:22 UTC, j3qq4hch commented
I give up. I will remove C-sections

2016-12-27 16:24 UTC, pavel-kirienko commented
Embrace C++ Alexander.

![image](https://cloud.githubusercontent.com/assets/3298404/21503636/0a50f4dc-cc6a-11e6-9df4-b2202565407c.png)

2016-12-27 16:25 UTC, j3qq4hch commented
Sounds like 
-Hey, mister, do you have a minute to discuss our holy god Jesus Christ?

2016-12-27 16:28 UTC, pavel-kirienko commented
Don't blow my cover please.

2017-01-02 03:14 UTC, pavel-kirienko commented
Is it ready for review Alexander?

2017-01-02 07:24 UTC, j3qq4hch commented
I'm about to add some more today. Wait a bit

2017-08-31 18:25 UTC, pavel-kirienko commented
@j3qq4hch if you have anything worth saving in your branch, please save it locally, then delete it.

2017-08-31 18:27 UTC, closed without merging